# Generated by Django 4.2.13 on 2024-07-09 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
