# Generated by Django 4.2.14 on 2024-07-29 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG_APP', '0004_blog_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(default=None, help_text='Brief description of the blog post.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the blog post.', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(default='tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the blog post was created.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, help_text='Profile picture of the user.', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
